spring:
  datasource:
    url: jdbc:h2:mem:pricingdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # <-- this is to ensure that data.sql is executed after the table is created
  h2:
    console:
      enabled: true
      path: /h2-console
# Connect to db
# JDBC URL: jdbc:h2:mem:pricingdb
